export const colors = {
  dark: {
    surface: "#0b1326",
    surfaceDim: "#0b1326",
    surfaceBright: "#31394d",
    surfaceContainerLowest: "#060e20",
    surfaceContainerLow: "#131b2e",
    surfaceContainer: "#171f33",
    surfaceContainerHigh: "#222a3d",
    surfaceContainerHighest: "#2d3449",
    onSurface: "#dae2fd",
    onSurfaceVariant: "#ccc3d8",
    inverseSurface: "#dae2fd",
    inverseOnSurface: "#283044",
    outline: "#958da1",
    outlineVariant: "#4a4455",
    surfaceTint: "#d2bbff",
    primary: "#d2bbff",
    onPrimary: "#3f008e",
    primaryContainer: "#7c3aed",
    onPrimaryContainer: "#ede0ff",
    inversePrimary: "#732ee4",
    secondary: "#adc6ff",
    onSecondary: "#002e6a",
    secondaryContainer: "#0566d9",
    onSecondaryContainer: "#e6ecff",
    tertiary: "#4edea3",
    onTertiary: "#003824",
    tertiaryContainer: "#007650",
    onTertiaryContainer: "#76ffc2",
    error: "#ffb4ab",
    onError: "#690005",
    errorContainer: "#93000a",
    onErrorContainer: "#ffdad6",
    primaryFixed: "#eaddff",
    primaryFixedDim: "#d2bbff",
    onPrimaryFixed: "#25005a",
    onPrimaryFixedVariant: "#5a00c6",
    secondaryFixed: "#d8e2ff",
    secondaryFixedDim: "#adc6ff",
    onSecondaryFixed: "#001a42",
    onSecondaryFixedVariant: "#004395",
    tertiaryFixed: "#6ffbbe",
    tertiaryFixedDim: "#4edea3",
    onTertiaryFixed: "#002113",
    onTertiaryFixedVariant: "#005236",
    background: "#0b1326",
    onBackground: "#dae2fd",
    surfaceVariant: "#2d3449",
    // Brand Specific Translucencies
    accentGradient: ["#7c3aed", "#0566d9"],
    glassFill: "rgba(45, 52, 73, 0.7)",
    glassBorder: "rgba(255, 255, 255, 0.12)",
    shadowAmbient: "rgba(210, 187, 255, 0.3)",
  },
  // Luminous Minimalist Light Mode (Theme: Modern Corporate)
  light: {
    surface: "#f9f9ff",
    surfaceDim: "#cfdaf2",
    surfaceBright: "#f9f9ff",
    surfaceContainerLowest: "#ffffff",
    surfaceContainerLow: "#f0f3ff",
    surfaceContainer: "#e7eeff",
    surfaceContainerHigh: "#dee8ff",
    surfaceContainerHighest: "#d8e3fb",
    onSurface: "#111c2d",
    onSurfaceVariant: "#4a4455",
    inverseSurface: "#263143",
    inverseOnSurface: "#ecf1ff",
    outline: "#7b7487",
    outlineVariant: "#ccc3d8",
    surfaceTint: "#732ee4",
    primary: "#630ed4", // Action Core
    onPrimary: "#ffffff",
    primaryContainer: "#7c3aed", // Vibrant Violet
    onPrimaryContainer: "#ede0ff",
    inversePrimary: "#d2bbff",
    secondary: "#4648d4",
    onSecondary: "#ffffff",
    secondaryContainer: "#6063ee",
    onSecondaryContainer: "#fffbff",
    tertiary: "#005479",
    onTertiary: "#ffffff",
    tertiaryContainer: "#006d9c",
    onTertiaryContainer: "#cfe9ff",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdad6",
    onErrorContainer: "#93000a",
    primaryFixed: "#eaddff",
    primaryFixedDim: "#d2bbff",
    onPrimaryFixed: "#25005a",
    onPrimaryFixedVariant: "#5a00c6",
    secondaryFixed: "#e1e0ff",
    secondaryFixedDim: "#c0c1ff",
    onSecondaryFixed: "#07006c",
    onSecondaryFixedVariant: "#2f2ebe",
    tertiaryFixed: "#c9e6ff",
    tertiaryFixedDim: "#89ceff",
    onTertiaryFixed: "#001e2f",
    onTertiaryFixedVariant: "#004c6e",
    background: "#f9f9ff", // Clean canvas background
    onBackground: "#111c2d", // Charcoal for extreme readability
    surfaceVariant: "#d8e3fb",
    // Minimalist Layer Tokens
    borderLine: "#e2e8f0",
    dividerLine: "#f1f5f9",
    textMuted: "#64748b",
    shadowAmbientLevel2: "rgba(30, 41, 59, 0.05)",
    shadowAmbientLevel3: "rgba(30, 41, 59, 0.1)",
  },
};
